/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marian
 */
public class JosmTracerConfigGui extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
 JosmTracerConfigGui NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tracerUrlCheckBox = new javax.swing.JCheckBox();
        tracerUrlValueField = new javax.swing.JTextField();
        ruianUrlCheckBox = new javax.swing.JCheckBox();
        ruianUrlValueField = new javax.swing.JTextField();
        ruianAdjustCheckBox = new javax.swing.JCheckBox();
        ruianLatLabel = new javax.swing.JLabel();
        ruianLonLabel = new javax.swing.JLabel();
        ruianLatZeroLabel = new javax.swing.JLabel();
        ruianLonZeroLabel = new javax.swing.JLabel();
        ruianLatSignComboBox = new javax.swing.JComboBox();
        ruianLonSignComboBox = new javax.swing.JComboBox();
        ruianAdjustLatSpinner = new javax.swing.JSpinner();
        ruianAdjustLonSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        tracerAdjustLatSpinner = new javax.swing.JSpinner();
        tracerAdjustLonSpinner = new javax.swing.JSpinner();
        tracerLatSignComboBox = new javax.swing.JComboBox();
        tracerLonSignComboBox = new javax.swing.JComboBox();
        tracerLatZeroLabel = new javax.swing.JLabel();
        tracerLonZeroLabel = new javax.swing.JLabel();
        tracerLatLabel = new javax.swing.JLabel();
        tracerAdjustCheckBox = new javax.swing.JCheckBox();
        tracerLonLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        enabledModulesLabel = new javax.swing.JLabel();
        classicCheckBox = new javax.swing.JCheckBox();
        ruianCheckBox = new javax.swing.JCheckBox();

        tracerUrlCheckBox.setText("Custom Classic Tracer server url");
        tracerUrlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracerUrlCheckBoxActionPerformed(evt);
            }
        });

        tracerUrlValueField.setText("http://localhost:5050/");

        ruianUrlCheckBox.setText("Custom Ruian server url");
        ruianUrlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruianUrlCheckBoxActionPerformed(evt);
            }
        });

        ruianUrlValueField.setText("http://josm.poloha.net/");
        ruianUrlValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruianUrlValueFieldActionPerformed(evt);
            }
        });

        ruianAdjustCheckBox.setText("Adjust traced object position");
        ruianAdjustCheckBox.setToolTipText("");

        ruianLatLabel.setText("Lat:");

        ruianLonLabel.setText("Lon:");

        ruianLatZeroLabel.setText("0.0000");
        ruianLatZeroLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        ruianLonZeroLabel.setText("0.0000");

        ruianLatSignComboBox.setMaximumRowCount(2);
        ruianLatSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        ruianLonSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        ruianLonSignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruianLonSignComboBoxActionPerformed(evt);
            }
        });

        ruianAdjustLatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        ruianAdjustLatSpinner.setToolTipText("");

        ruianAdjustLonSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        ruianAdjustLonSpinner.setToolTipText("");

        tracerAdjustLatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        tracerAdjustLatSpinner.setToolTipText("");

        tracerAdjustLonSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        tracerAdjustLonSpinner.setToolTipText("");

        tracerLatSignComboBox.setMaximumRowCount(2);
        tracerLatSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        tracerLonSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        tracerLonSignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracerLonSignComboBoxActionPerformed(evt);
            }
        });

        tracerLatZeroLabel.setText("0.0000");
        tracerLatZeroLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tracerLonZeroLabel.setText("0.0000");

        tracerLatLabel.setText("Lat:");

        tracerAdjustCheckBox.setText("Adjust traced object position");
        tracerAdjustCheckBox.setToolTipText("");

        tracerLonLabel.setText("Lon:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        enabledModulesLabel.setText("Enabled modules:");

        classicCheckBox.setText("Classic");
        classicCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicCheckBoxActionPerformed(evt);
            }
        });

        ruianCheckBox.setSelected(true);
        ruianCheckBox.setText("RUIAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enabledModulesLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(classicCheckBox)
                        .addGap(34, 34, 34)
                        .addComponent(ruianCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(enabledModulesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classicCheckBox)
                    .addComponent(ruianCheckBox))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        enabledModulesLabel.getAccessibleContext().setAccessibleDescription("Select modules available for switching");
        classicCheckBox.getAccessibleContext().setAccessibleDescription("Use Classic (the original) tracer mode");
        ruianCheckBox.getAccessibleContext().setAccessibleDescription("Use RUIAN Tracer module");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tracerUrlCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tracerAdjustCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tracerLatLabel)
                                    .addComponent(tracerLonLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tracerLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tracerLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tracerLonZeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tracerAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tracerLatZeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tracerAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ruianAdjustCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ruianLatLabel)
                                    .addComponent(ruianLonLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ruianLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ruianLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ruianLatZeroLabel)
                                    .addComponent(ruianLonZeroLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ruianAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ruianAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ruianUrlCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tracerUrlValueField)
                                    .addComponent(ruianUrlValueField))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tracerUrlCheckBox)
                .addGap(4, 4, 4)
                .addComponent(tracerUrlValueField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tracerAdjustCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tracerLatLabel)
                        .addGap(12, 12, 12)
                        .addComponent(tracerLonLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tracerLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tracerLatZeroLabel)
                                .addComponent(tracerAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tracerLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(tracerLonZeroLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tracerAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ruianUrlCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruianUrlValueField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ruianAdjustCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ruianAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addComponent(ruianLatLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(ruianAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruianLonLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ruianLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ruianLatZeroLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruianLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(ruianLonZeroLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ruianLonSignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruianLonSignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruianLonSignComboBoxActionPerformed

    private void tracerLonSignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracerLonSignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracerLonSignComboBoxActionPerformed

    private void classicCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classicCheckBoxActionPerformed

    private void tracerUrlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracerUrlCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracerUrlCheckBoxActionPerformed

    private void ruianUrlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruianUrlCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruianUrlCheckBoxActionPerformed

    private void ruianUrlValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruianUrlValueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruianUrlValueFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox classicCheckBox;
    private javax.swing.JLabel enabledModulesLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox ruianAdjustCheckBox;
    private javax.swing.JSpinner ruianAdjustLatSpinner;
    private javax.swing.JSpinner ruianAdjustLonSpinner;
    private javax.swing.JCheckBox ruianCheckBox;
    private javax.swing.JLabel ruianLatLabel;
    private javax.swing.JComboBox ruianLatSignComboBox;
    private javax.swing.JLabel ruianLatZeroLabel;
    private javax.swing.JLabel ruianLonLabel;
    private javax.swing.JComboBox ruianLonSignComboBox;
    private javax.swing.JLabel ruianLonZeroLabel;
    private javax.swing.JCheckBox ruianUrlCheckBox;
    private javax.swing.JTextField ruianUrlValueField;
    private javax.swing.JCheckBox tracerAdjustCheckBox;
    private javax.swing.JSpinner tracerAdjustLatSpinner;
    private javax.swing.JSpinner tracerAdjustLonSpinner;
    private javax.swing.JLabel tracerLatLabel;
    private javax.swing.JComboBox tracerLatSignComboBox;
    private javax.swing.JLabel tracerLatZeroLabel;
    private javax.swing.JLabel tracerLonLabel;
    private javax.swing.JComboBox tracerLonSignComboBox;
    private javax.swing.JLabel tracerLonZeroLabel;
    private javax.swing.JCheckBox tracerUrlCheckBox;
    private javax.swing.JTextField tracerUrlValueField;
    // End of variables declaration//GEN-END:variables
}
