/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marian
 */
public class JosmTracerConfigGui extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
 JosmTracerConfigGui NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainConfigPanel = new javax.swing.JPanel();
        ModulesConfigPanel = new javax.swing.JPanel();
        AvilableModulesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AvailableModulesList = new javax.swing.JList();
        ModulesRightButton = new javax.swing.JButton();
        ModulesLeftButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        EnabledModulesList = new javax.swing.JList();
        ModulesUpButton = new javax.swing.JButton();
        ModulesDownButton = new javax.swing.JButton();
        EnabledModulesLabel = new javax.swing.JLabel();
        TracerConfigPanel = new javax.swing.JPanel();
        TracerUrlCheckBox = new javax.swing.JCheckBox();
        TracerUrlValueField = new javax.swing.JTextField();
        TracerAdjustCheckBox = new javax.swing.JCheckBox();
        TracerLatLabel = new javax.swing.JLabel();
        TracerLatSignComboBox = new javax.swing.JComboBox();
        TracerLatZeroLabel = new javax.swing.JLabel();
        TracerAdjustLatSpinner = new javax.swing.JSpinner();
        TracerAdjustLonSpinner = new javax.swing.JSpinner();
        TracerLonZeroLabel = new javax.swing.JLabel();
        TracerLonSignComboBox = new javax.swing.JComboBox();
        TracerLonLabel = new javax.swing.JLabel();
        RuianConfigPanel = new javax.swing.JPanel();
        RuianUrlCheckBox = new javax.swing.JCheckBox();
        RuianUrlValueField = new javax.swing.JTextField();
        RuianAdjustCheckBox = new javax.swing.JCheckBox();
        RuianLatSignComboBox = new javax.swing.JComboBox();
        RuianAdjustLatSpinner = new javax.swing.JSpinner();
        RuianLatZeroLabel = new javax.swing.JLabel();
        RuianLonZeroLabel = new javax.swing.JLabel();
        RuianAdjustLonSpinner = new javax.swing.JSpinner();
        RuianLonLabel = new javax.swing.JLabel();
        RuianLatLabel = new javax.swing.JLabel();
        RuianLonSignComboBox = new javax.swing.JComboBox();

        ModulesConfigPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AvilableModulesLabel.setText("Available modules:");

        AvailableModulesList.setModel(new DefaultListModel());
        AvailableModulesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                AvailableModulesListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(AvailableModulesList);

        ModulesRightButton.setText(">>");
        ModulesRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulesRightButtonActionPerformed(evt);
            }
        });

        ModulesLeftButton.setText("<<");
        ModulesLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulesLeftButtonActionPerformed(evt);
            }
        });

        EnabledModulesList.setModel(new DefaultListModel());
        EnabledModulesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                EnabledModulesListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(EnabledModulesList);

        ModulesUpButton.setText("Up");
        ModulesUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulesUpButtonActionPerformed(evt);
            }
        });

        ModulesDownButton.setText("Down");
        ModulesDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulesDownButtonActionPerformed(evt);
            }
        });

        EnabledModulesLabel.setText("Enabled modules:");

        javax.swing.GroupLayout ModulesConfigPanelLayout = new javax.swing.GroupLayout(ModulesConfigPanel);
        ModulesConfigPanel.setLayout(ModulesConfigPanelLayout);
        ModulesConfigPanelLayout.setHorizontalGroup(
            ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModulesConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvilableModulesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ModulesUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModulesDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(ModulesRightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModulesLeftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnabledModulesLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ModulesConfigPanelLayout.setVerticalGroup(
            ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModulesConfigPanelLayout.createSequentialGroup()
                .addGroup(ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModulesConfigPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ModulesConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AvilableModulesLabel)
                            .addComponent(EnabledModulesLabel)))
                    .addGroup(ModulesConfigPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModulesConfigPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModulesConfigPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(ModulesUpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModulesRightButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModulesLeftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModulesDownButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TracerConfigPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TracerUrlCheckBox.setText("Custom Classic Tracer server url");
        TracerUrlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TracerUrlCheckBoxActionPerformed(evt);
            }
        });

        TracerUrlValueField.setText("http://localhost:5050/");

        TracerAdjustCheckBox.setText("Adjust traced object position");
        TracerAdjustCheckBox.setToolTipText("");

        TracerLatLabel.setText("Lat:");

        TracerLatSignComboBox.setMaximumRowCount(2);
        TracerLatSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        TracerLatZeroLabel.setText("0.0000");
        TracerLatZeroLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TracerAdjustLatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        TracerAdjustLatSpinner.setToolTipText("");

        TracerAdjustLonSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        TracerAdjustLonSpinner.setToolTipText("");

        TracerLonZeroLabel.setText("0.0000");

        TracerLonSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        TracerLonSignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TracerLonSignComboBoxActionPerformed(evt);
            }
        });

        TracerLonLabel.setText("Lon:");

        javax.swing.GroupLayout TracerConfigPanelLayout = new javax.swing.GroupLayout(TracerConfigPanel);
        TracerConfigPanel.setLayout(TracerConfigPanelLayout);
        TracerConfigPanelLayout.setHorizontalGroup(
            TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TracerUrlCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                        .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TracerAdjustCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TracerLatLabel)
                                    .addComponent(TracerLonLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TracerLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TracerLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                                        .addComponent(TracerLonZeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TracerAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                                        .addComponent(TracerLatZeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TracerAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TracerUrlValueField)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        TracerConfigPanelLayout.setVerticalGroup(
            TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TracerUrlCheckBox)
                .addGap(4, 4, 4)
                .addComponent(TracerUrlValueField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TracerAdjustCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                        .addComponent(TracerLatLabel)
                        .addGap(12, 12, 12)
                        .addComponent(TracerLonLabel))
                    .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                        .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TracerLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TracerLatZeroLabel)
                                .addComponent(TracerAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(TracerConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TracerLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TracerConfigPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(TracerLonZeroLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TracerConfigPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TracerAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RuianConfigPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        RuianUrlCheckBox.setText("Custom Ruian server url");
        RuianUrlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuianUrlCheckBoxActionPerformed(evt);
            }
        });

        RuianUrlValueField.setText("http://josm.poloha.net/");
        RuianUrlValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuianUrlValueFieldActionPerformed(evt);
            }
        });

        RuianAdjustCheckBox.setText("Adjust traced object position");
        RuianAdjustCheckBox.setToolTipText("");

        RuianLatSignComboBox.setMaximumRowCount(2);
        RuianLatSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        RuianAdjustLatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        RuianAdjustLatSpinner.setToolTipText("");

        RuianLatZeroLabel.setText("0.0000");
        RuianLatZeroLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        RuianLonZeroLabel.setText("0.0000");

        RuianAdjustLonSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        RuianAdjustLonSpinner.setToolTipText("");

        RuianLonLabel.setText("Lon:");

        RuianLatLabel.setText("Lat:");

        RuianLonSignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        RuianLonSignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuianLonSignComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RuianConfigPanelLayout = new javax.swing.GroupLayout(RuianConfigPanel);
        RuianConfigPanel.setLayout(RuianConfigPanelLayout);
        RuianConfigPanelLayout.setHorizontalGroup(
            RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RuianAdjustCheckBox)
                    .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RuianLatLabel)
                            .addComponent(RuianLonLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RuianLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RuianLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RuianLatZeroLabel)
                            .addComponent(RuianLonZeroLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RuianAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RuianAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(RuianUrlCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                        .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(RuianUrlValueField))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        RuianConfigPanelLayout.setVerticalGroup(
            RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RuianUrlCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RuianUrlValueField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RuianAdjustCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                                .addComponent(RuianAdjustLatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addComponent(RuianLatLabel))
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(RuianAdjustLonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RuianConfigPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RuianLonLabel))))
                    .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RuianLatSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RuianLatZeroLabel))
                        .addGroup(RuianConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RuianLonSignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RuianConfigPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(RuianLonZeroLabel)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainConfigPanelLayout = new javax.swing.GroupLayout(MainConfigPanel);
        MainConfigPanel.setLayout(MainConfigPanelLayout);
        MainConfigPanelLayout.setHorizontalGroup(
            MainConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RuianConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TracerConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModulesConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        MainConfigPanelLayout.setVerticalGroup(
            MainConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModulesConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TracerConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RuianConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainConfigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RuianLonSignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuianLonSignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuianLonSignComboBoxActionPerformed

    private void RuianUrlValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuianUrlValueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuianUrlValueFieldActionPerformed

    private void RuianUrlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuianUrlCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuianUrlCheckBoxActionPerformed

    private void TracerLonSignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TracerLonSignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TracerLonSignComboBoxActionPerformed

    private void TracerUrlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TracerUrlCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TracerUrlCheckBoxActionPerformed

    private void ModulesDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulesDownButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModulesDownButtonActionPerformed

    private void ModulesUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulesUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModulesUpButtonActionPerformed

    private void ModulesLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulesLeftButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModulesLeftButtonActionPerformed

    private void ModulesRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulesRightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModulesRightButtonActionPerformed

    private void EnabledModulesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_EnabledModulesListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_EnabledModulesListValueChanged

    private void AvailableModulesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_AvailableModulesListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_AvailableModulesListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AvailableModulesList;
    private javax.swing.JLabel AvilableModulesLabel;
    private javax.swing.JLabel EnabledModulesLabel;
    private javax.swing.JList EnabledModulesList;
    private javax.swing.JPanel MainConfigPanel;
    private javax.swing.JPanel ModulesConfigPanel;
    private javax.swing.JButton ModulesDownButton;
    private javax.swing.JButton ModulesLeftButton;
    private javax.swing.JButton ModulesRightButton;
    private javax.swing.JButton ModulesUpButton;
    private javax.swing.JCheckBox RuianAdjustCheckBox;
    private javax.swing.JSpinner RuianAdjustLatSpinner;
    private javax.swing.JSpinner RuianAdjustLonSpinner;
    private javax.swing.JPanel RuianConfigPanel;
    private javax.swing.JLabel RuianLatLabel;
    private javax.swing.JComboBox RuianLatSignComboBox;
    private javax.swing.JLabel RuianLatZeroLabel;
    private javax.swing.JLabel RuianLonLabel;
    private javax.swing.JComboBox RuianLonSignComboBox;
    private javax.swing.JLabel RuianLonZeroLabel;
    private javax.swing.JCheckBox RuianUrlCheckBox;
    private javax.swing.JTextField RuianUrlValueField;
    private javax.swing.JCheckBox TracerAdjustCheckBox;
    private javax.swing.JSpinner TracerAdjustLatSpinner;
    private javax.swing.JSpinner TracerAdjustLonSpinner;
    private javax.swing.JPanel TracerConfigPanel;
    private javax.swing.JLabel TracerLatLabel;
    private javax.swing.JComboBox TracerLatSignComboBox;
    private javax.swing.JLabel TracerLatZeroLabel;
    private javax.swing.JLabel TracerLonLabel;
    private javax.swing.JComboBox TracerLonSignComboBox;
    private javax.swing.JLabel TracerLonZeroLabel;
    private javax.swing.JCheckBox TracerUrlCheckBox;
    private javax.swing.JTextField TracerUrlValueField;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
